const actionTypes = {

    // MODALS
    MODAL_CHOICE: 'MODAL_CHOICE',
    SIGN_UP_MODAL: 'SIGN_UP_MODAL',
    SIGN_IN_MODAL: 'SIGN_IN_MODAL',
    SIGN_UP_FORM: 'SIGN_UP_FORM',

    // VRI
    SAVE_VRI_AJAX: 'SAVE_VRI_AJAX',
    GET_USER_VRI_AJAX: 'GET_USER_VRI_AJAX',
    GET_VRIS_AJAX: 'GET_VRIS_AJAX',

    // NEWS
    DISPLAY_NEWS_AJAX: 'DISPLAY_NEWS_AJAX',
    DISPLAY_IMAGE: 'DISPLAY_IMAGE',

    // AUTH
    SIGN_IN_AJAX: 'SIGN_IN_AJAX',
    SIGN_UP_AJAX: 'SIGN_UP_AJAX',
    USER_DATA_AJAX: 'USER_DATA_AJAX',

    // AJAX CALLS
    BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
    AJAX_CALL_ERROR: 'AJAX_CALL_ERROR'

};

export default actionTypes;
